### ISSUE TITLE
Login Fedex Fail?

### ISSUE THREAD

**Issue by nmquan-dev** [kidd0203/Utilities#5]
I have a username and password when I register an account on Fedex website.
I use username and password input to _ConnectionString.SetupFedExCredential("username", "password");_, but I recieve a status "Authentication Failed".
Please help me!!!

**Comment by kidd0203** [comment]
Hi, 

You need to have a username and password for Fedex api calling instead of accessing Fedex website.

Best Regards,
CJ

**Comment by nmquan-dev** [comment]
Thanks for the support!!!
Best Regards

2017-01-09 22:12 GMT+07:00 kidd0203 <notifications@github.com>:

**Comment by parabola949** [comment]
I'm having the same issue.  I have verified I am using my production API key and the API password that was emailed to me by FedEx.  Please advise.  I have an api key, account number, meter number, and password.  I've tried all sorts of combinations of these things, nothing works, authentication failed every time
